"""
Reads paired evaluation score vectors, computes paired t-tests & Wilcoxon signed-rank tests,
renders Markdown summaries, and exports publication-ready statistical metric charts.
"""

import argparse
import json
import logging
from pathlib import Path
from typing import Dict, Any

import matplotlib.pyplot as plt
import numpy as np

from omnipeft.analytics.hypothesis_testing import HypothesisTestingEngine

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("omnipeft.hypothesis_runner")


def generate_visualization_charts(
    scores_base: list,
    scores_fused: list,
    output_dir: Path,
) -> None:
    """Generate distribution boxplots and score delta histogram plots."""
    plt.style.use("seaborn-v0_8-whitegrid" if "seaborn-v0_8-whitegrid" in plt.style.available else "default")
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Plot 1: Score Distribution Boxplot
    axes[0].boxplot([scores_base, scores_fused], labels=["Baseline", "Fused PEFT"], patch_artist=True)
    axes[0].set_title("Metric Distribution Comparison")
    axes[0].set_ylabel("Score (ROUGE-L)")

    # Plot 2: Paired Score Differences Histogram
    diffs = np.array(scores_fused) - np.array(scores_base)
    axes[1].hist(diffs, bins=15, color="skyblue", edgecolor="black")
    axes[1].axvline(0.0, color="red", linestyle="--", linewidth=1.5, label="Zero Delta")
    axes[1].axvline(float(np.mean(diffs)), color="green", linestyle="-", linewidth=2, label=f"Mean Delta (+{np.mean(diffs):.2f})")
    axes[1].set_title("Paired Score Difference Distribution (Fused - Base)")
    axes[1].set_xlabel("Delta")
    axes[1].set_ylabel("Frequency")
    axes[1].legend()

    plt.tight_layout()
    chart_path = output_dir / "hypothesis_test_distribution.png"
    plt.savefig(chart_path, dpi=300)
    plt.close()
    logger.info("Metric distribution chart generated at: %s", chart_path)


def main() -> None:
    """Read evaluation vectors, execute hypothesis testing, and output artifacts."""
    parser = argparse.ArgumentParser(description="OmniPEFT Hypothesis Testing Runner")
    parser.add_argument(
        "--eval_file",
        type=str,
        default="./artifacts/evaluation_results/raw_evaluation_vectors.json",
        help="Path to raw evaluation vectors JSON file",
    )
    parser.add_argument("--output_dir", type=str, default="./artifacts/evaluation_results")
    parser.add_argument("--alpha", type=float, default=0.01, help="Significance threshold")

    args = parser.parse_args()
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. Load paired sample vectors
    with open(args.eval_file, "r", encoding="utf-8") as f:
        eval_data: Dict[str, Any] = json.load(f)

    scores_base = eval_data["scores_base"]
    scores_fused = eval_data["scores_fused"]

    # 2. Execute Hypothesis Testing Engine
    engine = HypothesisTestingEngine(alpha_threshold=args.alpha)
    test_result = engine.evaluate_significance(scores_base, scores_fused)

    # 3. Save JSON Report
    report_data = {
        "models": {
            "base": eval_data.get("base_model", "baseline"),
            "fused": eval_data.get("fused_model", "fused_peft"),
        },
        "aggregate_metrics": {
            "base": eval_data.get("base_results", {}),
            "fused": eval_data.get("fused_results", {}),
        },
        "statistical_hypothesis_test": test_result.to_dict(),
    }

    json_report_path = out_dir / "statistical_significance_report.json"
    with open(json_report_path, "w", encoding="utf-8") as f:
        json.dump(report_data, f, indent=2)

    # 4. Save Markdown Benchmarking Summary Table
    md_content = f"""# OmniPEFT Evaluation & Statistical Significance Report

## Aggregate Benchmarking Summary

| Metric | Baseline Model | Fused PEFT Model | Performance Delta |
| :--- | :---: | :---: | :---: |
| **Mean Score** | `{test_result.base_mean:.4f}` | `{test_result.fused_mean:.4f}` | **`+{test_result.mean_delta:.4f}`** |

## Statistical Hypothesis Testing Results ($p < {args.alpha}$)

* **Paired Student's t-test Statistic**: `{test_result.t_statistic:.4f}`
* **Paired Student's t-test $p$-value**: `{test_result.t_test_p_value:.6e}`
* **Wilcoxon Signed-Rank Statistic**: `{test_result.wilcoxon_statistic:.4f}`
* **Wilcoxon Signed-Rank $p$-value**: `{test_result.wilcoxon_p_value:.6e}`
* **Effect Size (Cohen's $d$)**: `{test_result.cohens_d:.4f}`
* **Statistically Significant Improvement ($p < {args.alpha}$)**: **`{test_result.is_statistically_significant}`**

---
*Report automatically generated by OmniPEFT Phase 5 Evaluation Suite.*
"""
    md_report_path = out_dir / "summary_table.md"
    with open(md_report_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    # 5. Generate Metric Visualizations
    generate_visualization_charts(scores_base, scores_fused, out_dir)

    logger.info("Hypothesis test execution finished successfully.")
    logger.info("Summary Table: %s", md_report_path)
    logger.info("JSON Report: %s", json_report_path)


if __name__ == "__main__":
    main()